<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice Rule</name>
  <uuid>c2391443-3cd6-45ea-88e8-59e766c85464</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then	
    set the dailyadvicemessage of decision to  "Hello " + Name + "!" + 'Weather Advice' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
