<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>eb75dd57-5808-41f1-9af6-53220edc7cb7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set the dailyadvicemessage of decision to "Sorry, we dont have enough information to provide a response." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
