<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>e6936b3a-b374-413c-ab18-2f317faedea8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Sorry, we do not have enough information to provide a response." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
